#!/bin/bash
###############################################################################
# Samsung Galaxy A14 Debloat — CUSTOM for PhoneAgent
# KEEPS: LinkedIn, Chrome, Gmail, Play Store, Camera, Messages, Contacts,
#        Phone, Settings, Files, Gallery, Keyboard, Clock, Calculator
###############################################################################

set -uo pipefail

CMD="adb shell pm uninstall -k --user 0"

echo "============================================="
echo " PhoneAgent Debloat — Samsung Galaxy A14"
echo "============================================="

# Verify ADB connection
if ! adb devices 2>/dev/null | grep -q "device$"; then
    echo "[ERROR] No device found!"
    exit 1
fi

DEVICE=$(adb shell getprop ro.product.model 2>/dev/null | tr -d '\r')
echo "[OK] Connected to: $DEVICE"
echo ""

REMOVED=0
FAILED=0

remove() {
    if $CMD "$1" 2>/dev/null | grep -q "Success"; then
        echo "[OK] $1  # $2"
        REMOVED=$((REMOVED + 1))
    else
        FAILED=$((FAILED + 1))
    fi
}

echo "=== BIXBY ==="
remove com.samsung.android.bixby.agent "Bixby Voice"
remove com.samsung.android.bixby.agent.dummy "Bixby placeholder"
remove com.samsung.android.bixby.service "Bixby service"
remove com.samsung.android.bixby.wakeup "Hi Bixby wake-up"
remove com.samsung.android.bixbyvision.framework "Bixby Vision"
remove com.samsung.android.bixby.es.globalaction "Bixby global actions"
remove com.samsung.android.bixby.plmsync "Bixby plan sync"
remove com.samsung.android.bixby.voiceinput "Bixby voice input"
remove com.samsung.android.app.settings.bixby "Bixby settings"
remove com.samsung.android.visionintelligence "Bixby Vision AI"
remove com.samsung.systemui.bixby "Bixby SystemUI"
remove com.samsung.systemui.bixby2 "Bixby SystemUI v2"

echo ""
echo "=== AR / EMOJI / STICKERS ==="
remove com.samsung.android.aremoji "AR Emoji"
remove com.samsung.android.aremojieditor "AR Emoji editor"
remove com.samsung.android.arzone "AR Zone"
remove com.samsung.android.ardrawing "AR Doodle"
remove com.samsung.android.livestickers "Live Stickers"
remove com.samsung.android.stickercenter "Sticker Center"
remove com.samsung.android.stickerplugin "Sticker plugin"
remove com.sec.android.mimage.avatarstickers "Avatar stickers"
remove com.sec.android.mimage.avatar.stickers "Avatar stickers alt"
remove com.samsung.android.app.camera.sticker.facear.preload "Face AR sticker"
remove com.samsung.android.app.camera.sticker.facear3d.preload "3D face sticker"
remove com.samsung.android.app.camera.sticker.facearavatar.preload "Avatar sticker"
remove com.samsung.android.app.camera.sticker.facearframe.preload "Frame sticker"
remove com.samsung.android.app.camera.sticker.stamp.preload "Stamp sticker"

echo ""
echo "=== THEMES / WALLPAPERS ==="
remove com.samsung.android.themestore "Galaxy Themes"
remove com.samsung.android.themecenter "Theme Center"
remove com.samsung.android.dynamiclock "Dynamic Lock Screen"
remove com.samsung.android.keyguardwallpaperupdator "Lock wallpaper updater"
remove com.android.wallpaper.livepicker "Live wallpaper picker"
remove com.android.wallpapercropper "Wallpaper cropper"

echo ""
echo "=== SAMSUNG CLOUD / SYNC ==="
remove com.samsung.android.scloud "Samsung Cloud"
remove com.samsung.android.mobileservice "Samsung Group Sharing"
remove com.samsung.storyservice "Story Service"
remove com.samsung.android.allshare.service.mediashare "Media share"
remove com.samsung.android.allshare.service.fileshare "File share"
remove com.samsung.android.app.simplesharing "Link Sharing"
remove com.samsung.android.privateshare "Private Share"

echo ""
echo "=== SAMSUNG PAY ==="
remove com.samsung.android.spay "Samsung Pay"
remove com.samsung.android.spayfw "Samsung Pay framework"
remove com.samsung.android.coldwalletservice "Blockchain Wallet"
remove com.samsung.android.kgclient "Pay device service"

echo ""
echo "=== GAME LAUNCHER ==="
remove com.samsung.android.game.gamehome "Game Launcher"
remove com.samsung.android.game.gametools "Game Tools"
remove com.samsung.android.game.gos "Game Optimizing Service"
remove com.samsung.android.gametuner.thin "Game Tuner"
remove com.enhance.gameservice "Game enhancement"
remove com.sec.android.app.gamehub "Game Hub"

echo ""
echo "=== DEX / LINK TO WINDOWS ==="
remove com.samsung.android.mdx "Link to Windows"
remove com.samsung.android.mdx.kit "Link to Windows kit"
remove com.samsung.android.mdx.quickboard "Link to Windows panel"
remove com.sec.android.app.desktoplauncher "DeX launcher"
remove com.sec.android.app.dexonpc "DeX on PC"
remove com.sec.android.desktopmode.uiservice "DeX UI"
remove com.samsung.desktopsystemui "DeX system UI"

echo ""
echo "=== KIDS ==="
remove com.samsung.android.kidsinstaller "Kids installer"
remove com.sec.android.app.kidshome "Kids Home"

echo ""
echo "=== KNOX ==="
remove com.samsung.android.knox.analytics.uploader "Knox analytics"
remove com.sec.enterprise.knox.cloudmdm.smdms "Knox enrollment"
remove com.samsung.knox.securefolder "Secure Folder"
remove com.samsung.knox.securefolder.setuppage "Secure Folder setup"
remove com.samsung.android.knox.zt.framework "Knox Zero Trust"
remove com.samsung.knox.appsupdateagent "Knox updates"
remove com.samsung.knox.rcp.components "Knox RCP"
remove com.samsung.klmsagent "Knox License Manager"

echo ""
echo "=== SAMSUNG PASS ==="
remove com.samsung.android.samsungpass "Samsung Pass"
remove com.samsung.android.samsungpassautofill "Samsung Pass autofill"

echo ""
echo "=== SMART SWITCH ==="
remove com.sec.android.easyMover "Smart Switch"
remove com.sec.android.easyMover.Agent "Smart Switch agent"
remove com.samsung.android.smartswitchassistant "Smart Switch assistant"
remove com.samsung.android.easysetup "Easy Setup"

echo ""
echo "=== SAMSUNG MISC ==="
remove com.samsung.android.app.spage "Samsung Daily"
remove com.samsung.android.app.tips "Samsung Tips"
remove com.samsung.android.voc "Samsung Members"
remove com.samsung.android.app.reminder "Samsung Reminder"
remove com.samsung.android.rubin.app "Customization tracking"
remove com.samsung.android.beaconmanager "Beacon Manager"
remove com.samsung.android.forest "Digital Wellbeing Samsung"
remove com.samsung.android.wellbeing "Digital Wellbeing alt"
remove com.samsung.android.app.cocktailbarservice "Edge Panels"
remove com.samsung.android.app.taskedge "Tasks Edge"
remove com.samsung.android.app.appsedge "Apps Edge"
remove com.samsung.android.app.clipboardedge "Clipboard Edge"
remove com.samsung.android.app.sbrowseredge "Browser Edge"
remove com.samsung.android.da.daagent "Dual Messenger"
remove com.samsung.android.fmm "Find My Mobile"
remove com.samsung.android.fmmm "Find My Mobile module"
remove com.samsung.android.app.find "SmartThings Find"
remove com.samsung.android.app.sharelive "Quick Share"
remove com.samsung.android.aware.service "Nearby awareness"
remove com.samsung.android.service.peoplestripe "People Edge"
remove com.samsung.android.authfw "Samsung Auth"
remove com.samsung.android.tvplus "Samsung TV Plus"
remove com.samsung.android.oneconnect "SmartThings"
remove com.samsung.android.app.watchmanager "Galaxy Wearable"
remove com.samsung.android.app.watchmanagerstub "Galaxy Wearable stub"
remove com.sec.android.app.billing "Samsung billing"
remove com.samsung.android.dkey "Digital Key"
remove com.samsung.android.dqagent "Samsung diagnostic"
remove com.samsung.android.ipsgeofence "Geofence tracking"
remove com.samsung.android.smartsuggestions "Smart Suggestions"
remove com.samsung.android.service.stplatform "ST platform"
remove com.samsung.android.mdecservice "Samsung marketing"
remove com.samsung.android.mcfds "MCF device service"
remove com.samsung.android.networkdiagnostic "Network diagnostic"
remove com.samsung.android.scpm "Security policy"
remove com.samsung.android.scs "Samsung Cloud sync"
remove com.samsung.android.securitylogagent "Security log"
remove com.samsung.android.mapsagent "Samsung Maps agent"
remove com.samsung.android.app.omcagent "OMC agent"
remove com.samsung.android.app.parentalcare "Parental Care"
remove com.samsung.android.app.separation "App separation"
remove com.samsung.android.sdk.handwriting "Handwriting SDK"
remove com.samsung.android.sm.devicesecurity "McAfee security"
remove com.samsung.android.sm.policy "Security policy"
remove com.samsung.android.fast "Samsung Fast setup"
remove com.samsung.sree "SREE service"
remove com.samsung.safetyinformation "Safety Information"
remove com.samsung.android.app.ledbackcover "LED back cover"
remove com.samsung.android.app.ledcoverdream "LED cover dream"
remove com.sec.android.cover.ledcover "LED cover"
remove com.samsung.android.service.livedrawing "Live drawing"
remove com.samsung.android.app.filterinstaller "Camera filter installer"
remove com.samsung.android.app.galaxyfinder "Finder"
remove com.samsung.android.tripwidget "Trip widget"
remove com.samsung.android.visionarapps "Vision AR"
remove com.samsung.android.visioncloudagent "Vision cloud"
remove com.samsung.android.setting.multisound "Multi sound"
remove com.samsung.android.app.vrsetupwizardstub "VR Setup"
remove com.samsung.android.hmt.vrshell "Gear VR"
remove com.samsung.android.hmt.vrsvc "Gear VR service"
remove com.samsung.android.service.travel "Travel service"
remove com.samsung.android.dlp.service "DLP service"
remove com.samsung.android.drivelink.stub "Drive Link"
remove com.samsung.android.app.mirrorlink "MirrorLink"
remove com.samsung.android.aircommandmanager "Air Command"
remove com.samsung.android.widgetapp.yahooedge.finance "Yahoo Finance widget"
remove com.samsung.android.widgetapp.yahooedge.sport "Yahoo Sports widget"
remove com.sec.android.widgetapp.easymodecontactswidget "Easy Mode widget"
remove com.sec.samsung.android.widgetapp.samsungapps "Galaxy Essentials widget"
remove com.sec.android.widgetapp.webmanual "User Manual widget"
remove com.samsung.android.bbc.bbcagent "BBC agent"
remove com.samsung.android.app.advsounddetector "Sound detector"
remove com.samsung.android.app.storyalbumwidget "Story Album widget"
remove com.samsung.app.highlightplayer "Highlight player"
remove com.samsung.daydream.customization "Daydream"
remove com.samsung.dcmservice "DCM service"
remove com.samsung.enhanceservice "Enhance service"
remove com.samsung.faceservice "Face service"
remove com.samsung.fresco.logging "Fresco logging"
remove com.samsung.groupcast "Group Cast"
remove com.samsung.hs20provider "HS20 provider"
remove com.samsung.ipservice "IP service"
remove com.samsung.voiceserviceplatform "Voice platform"
remove com.samsung.svoice.sync "S Voice sync"
remove com.samsung.android.svoice "S Voice"
remove com.samsung.android.svoiceime "S Voice IME"
remove com.samsung.ucs.agent.ese "UCS agent"
remove com.samsung.SMT "Samsung TTS"
remove com.samsung.aasaservice "AASA service"
remove com.sec.android.app.apex "Samsung APEX"
remove com.sec.android.app.applinker "App Linker"
remove com.sec.android.app.magnifier "Magnifier"
remove com.sec.android.app.ocr "OCR"
remove com.sec.android.app.parser "Parser"
remove com.sec.android.app.personalization "Personalization"
remove com.sec.android.app.ringtoneBR "Ringtone BR"
remove com.sec.android.app.safetyassurance "Safety assurance"
remove com.sec.android.app.soundalive "SoundAlive"
remove com.sec.android.app.sysscope "SysScope"
remove com.sec.android.app.tourviewer "Tour Viewer"
remove com.sec.android.app.translator "Translator"
remove com.sec.android.app.ve.vebgm "Video editor BGM"
remove com.sec.android.app.wfdbroker "WiFi Direct broker"
remove com.sec.android.app.withtv "Samsung TV"
remove com.samsung.android.app.withtv "Samsung TV alt"
remove com.sec.android.app.wlantest "WLAN test"
remove com.sec.android.diagmonagent "Diagnostic monitor"
remove com.sec.android.mimage.gear360editor "Gear 360 editor"
remove com.sec.android.mimage.photoretouching "Photo retouching"
remove com.sec.android.ofviewer "Office viewer"
remove com.sec.android.provider.snote "S Note"
remove com.sec.android.easyonehand "One Hand Operation"
remove com.sec.android.emergencylauncher "Emergency launcher"
remove com.sec.android.app.SmartClipEdgeService "Smart Clip"
remove com.sec.android.app.quicktool "Quick Tools"
remove com.sec.spp.push "Samsung Push Service"
remove com.sec.android.app.chromecustomizations "Chrome customizations"
remove com.policydm "Policy DM"
remove com.samsung.sec.android.application.csc "CSC app"
remove com.val.hardware "Hardware diagnostic"
remove com.wsomacp "Email config"

echo ""
echo "=== SAMSUNG INTERNET BROWSER (koristis Chrome) ==="
remove com.sec.android.app.sbrowser "Samsung Internet"
remove com.sec.android.app.sbrowser.lite "Samsung Internet Lite"

echo ""
echo "=== SAMSUNG EMAIL (koristis Gmail) ==="
remove com.samsung.android.email.provider "Samsung Email"
remove com.android.email "Android Email"
remove com.android.exchange "Exchange service"

echo ""
echo "=== SAMSUNG HEALTH ==="
remove com.sec.android.app.shealth "Samsung Health"

echo ""
echo "=== SAMSUNG NOTES ==="
remove com.samsung.android.app.notes "Samsung Notes"

echo ""
echo "=== FACEBOOK ==="
remove com.facebook.appmanager "Facebook App Manager"
remove com.facebook.services "Facebook Services"
remove com.facebook.system "Facebook System"
remove com.facebook.katana "Facebook app"

echo ""
echo "=== MICROSOFT ==="
remove com.microsoft.appmanager "Microsoft App Manager"
remove com.microsoft.skydrive "OneDrive"
remove com.microsoft.office.excel "Excel"
remove com.microsoft.office.word "Word"
remove com.microsoft.office.powerpoint "PowerPoint"
remove com.microsoft.office.officehubrow "Office hub"
remove com.microsoft.office.outlook "Outlook"

echo ""
echo "=== NETFLIX / SPOTIFY / AMAZON ==="
remove com.netflix.mediaclient "Netflix"
remove com.netflix.partner.activation "Netflix activation"
remove com.spotify.music "Spotify"
remove com.amazon.fv "Amazon FreeVee"
remove com.amazon.kindle "Kindle"
remove com.amazon.mShop.android "Amazon Shopping"
remove com.amazon.mp3 "Amazon Music"
remove com.amazon.venezia "Amazon App Store"

echo ""
echo "=== 3RD PARTY BLOAT ==="
remove de.axelspringer.yana.zeropage "Upday news"
remove com.hiya.star "Hiya caller ID"
remove com.imdb.mobile "IMDb"
remove com.audible.application "Audible"
remove com.blurb.checkout "Blurb"
remove com.cnn.mobile.android.phone.edgepanel "CNN Edge"
remove com.flipboard.app "Flipboard"
remove com.flipboard.boxer.app "Flipboard Briefing"
remove com.gotv.nflgamecenter.us.lite "NFL"
remove com.hancom.office.editor.hidden "Hancom Office"
remove com.infraware.polarisoffice5 "Polaris Office"
remove com.mobeam.barcodeService "Mobeam barcode"
remove com.sec.penup "PenUp"
remove com.sec.android.app.voicenote "Voice Recorder"

echo ""
echo "=== GOOGLE BLOAT (keeping Chrome, Gmail, Play Store) ==="
remove com.google.android.apps.tachyon "Google Meet"
remove com.google.android.apps.youtube.music "YouTube Music"
remove com.google.android.apps.docs "Google Docs"
remove com.google.android.apps.books "Play Books"
remove com.google.android.apps.magazines "Play Magazines"
remove com.google.android.apps.photos "Google Photos"
remove com.google.android.apps.plus "Google+"
remove com.google.android.apps.bard "Gemini"
remove com.google.android.videos "Google TV"
remove com.google.android.talk "Hangouts"
remove com.google.android.googlequicksearchbox "Google Search widget"
remove com.google.ar.core "AR Core"
remove com.google.vr.vrcore "VR Core"
remove com.google.android.feedback "Google feedback"
remove com.google.android.printservice.recommendation "Print service"
remove com.google.android.apps.walletnfcrel "Google Wallet"
remove com.google.android.projection.gearhead "Android Auto"
remove com.google.android.apps.turbo "Device Health"
remove com.google.android.apps.restore "Google restore"
remove com.google.android.health.connect.backuprestore "Health Connect backup"
remove com.google.android.healthconnect.controller "Health Connect"
remove com.google.android.partnersetup "Partner Setup"
remove com.google.android.onetimeinitializer "Google initializer"
# KEEPING: com.google.android.gm (Gmail)
# KEEPING: com.android.chrome (Chrome)
# KEEPING: com.android.vending (Play Store)
# KEEPING: com.google.android.youtube (YouTube)
# KEEPING: com.google.android.apps.maps (Google Maps)
# KEEPING: com.google.android.gms (Play Services)
# KEEPING: com.google.android.gsf (Google Services Framework)

echo ""
echo "=== ANDROID SYSTEM BLOAT ==="
remove com.android.bookmarkprovider "Bookmark provider"
remove com.android.dreams.basic "Screensaver"
remove com.android.dreams.phototable "Photo screensaver"
remove com.android.hotwordenrollment.okgoogle "OK Google"
remove com.android.hotwordenrollment.xgoogle "Hey Google"
remove com.android.providers.partnerbookmarks "Partner bookmarks"
remove com.android.egg "Easter egg"
remove com.android.backupconfirm "Backup confirm"
remove com.android.bips "Print service"
remove com.android.printspooler "Print spooler"
remove com.android.providers.userdictionary "User dictionary"
remove com.android.sharedstoragebackup "Storage backup"
remove com.android.managedprovisioning "Work profile"

echo ""
echo "=== ANT+ ==="
remove com.dsi.ant.plugins.antplus "ANT+ Plugins"
remove com.dsi.ant.sample.acquirechannels "ANT+ sample"
remove com.dsi.ant.server "ANT+ server"
remove com.dsi.ant.service.socket "ANT+ socket"

echo ""
echo "=== CARRIER BLOAT ==="
remove com.tmobile.echolocate "T-Mobile diagnostics"
remove com.tmobile.pr.adapt "T-Mobile Adapt"
remove com.tmobile.simlock "T-Mobile SIM lock"
remove com.tmobile.services "T-Mobile services"
remove com.tmobile.vvm.application "T-Mobile Voicemail"
remove com.ironsrc.aura.tmo "T-Mobile Aura"
remove com.vzw.apnlib "Verizon APN"
remove com.vzw.ecid "Verizon ECID"
remove com.vzw.hss.myverizon "My Verizon"
remove com.vzw.hs.android.modlite "Verizon module"
remove com.vcast.mediamanager "Verizon Media"
remove com.verizon.llkagent "Verizon LLK"
remove com.verizon.mips.services "Verizon MIPS"
remove com.vzw.visualvoicemail "Verizon Voicemail"
remove com.samsung.vzwapiservice "Samsung Verizon API"
remove com.verizon.obdm "Verizon OBD"
remove com.securityandprivacy.android.verizon.vms "Verizon VMS"
remove com.verizon.onetalk.dialer "Verizon OneTalk"
remove com.att.dh "AT&T Device Help"
remove com.att.callprotect "AT&T Call Protect"
remove com.att.tv "AT&T TV"
remove com.att.myWireless "AT&T Wireless"
remove com.att.visualvoicemail "AT&T Voicemail"
remove com.att.android.attsmartwifi "AT&T Smart WiFi"
remove com.boost.vvm "Boost Voicemail"
remove com.sprint.ms.smf.services "Sprint services"
remove com.sprint.provider "Sprint provider"
remove com.cricketwireless.mycricket "Cricket"
remove com.mizmowireless.tethering "Mizmo tethering"
remove com.aura.oobe.samsung.gl "Aura OOBE"
remove com.aura.oobe.samsung "Aura OOBE alt"
remove com.aura.oobe.att "Aura AT&T"
remove com.xfinitymobile.cometcarrierservice "Xfinity"
remove com.spectrum.cm.headless "Spectrum"
remove com.uscc.ecid "US Cellular"
remove com.cequint.ecid "Carrier ID"
remove com.sec.android.app.tfunlock "TracFone unlock"
remove com.sec.android.omc "OMC carrier config"

echo ""
echo "=== FONTS ==="
remove com.monotype.android.font.chococooky "Choco Cooky font"
remove com.monotype.android.font.cooljazz "Cool Jazz font"
remove com.monotype.android.font.foundation "Foundation font"
remove com.monotype.android.font.rosemary "Rosemary font"

echo ""
echo "============================================="
echo " DEBLOAT COMPLETE!"
echo " Removed: $REMOVED packages"
echo " Skipped: $FAILED (not found or already removed)"
echo "============================================="
echo ""
echo " KEPT: LinkedIn, Chrome, Gmail, YouTube, Maps,"
echo "       Play Store, Camera, Phone, Messages,"
echo "       Contacts, Gallery, Files, Keyboard,"
echo "       Clock, Calculator, Settings"
echo ""
echo " Reboot: adb reboot"
